cd /musl
sh basic_testcode.sh
sh busybox_testcode.sh
sh lua_testcode.sh
sh libctest_testcode.sh
sh ltp_testcode.sh
sh cyclictest_testcode.sh
sh iozone_testcode.sh
sh lmbench_testcode.sh
sh unixbench_testcode.sh
sh libcbench_testcode.sh
sh netperf_testcode.sh
sh iperf_testcode.sh
poweroff -f
