#!/usr/bin/env python3
"""Build a RAM-loaded StarFive FIT that audits or removes BuildStorm run dirs."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DELETE_CONFIRMATION = "DELETE-BUILDSTORM-RUNS"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for data in iter(lambda: source.read(4 * 1024 * 1024), b""):
            digest.update(data)
    return digest.hexdigest()


def maintenance_entry_script(action: str) -> str:
    if action not in {"list", "delete"}:
        raise ValueError(f"unsupported maintenance action: {action}")
    return f'''#!/musl/busybox sh
# Generated by scripts/build_starfive_sd_maintenance.py.
# The only deletable objects are non-symlink directories matching the exact
# /work/.whusp-buildstorm-runs/run-* boundary.  /work/tgoskits is never touched.

action="{action}"
runs_root="/work/.whusp-buildstorm-runs"
status=0
count=0

echo "STARFIVE_SD_MAINTENANCE_BEGIN action=$action root=$runs_root"

if [ -L "$runs_root" ]; then
    echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=runs_root_symlink"
    status=1
elif [ ! -e "$runs_root" ]; then
    echo "STARFIVE_SD_MAINTENANCE_EMPTY reason=runs_root_absent"
elif [ ! -d "$runs_root" ]; then
    echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=runs_root_not_directory"
    status=1
else
    for entry in "$runs_root"/run-*; do
        if [ ! -e "$entry" ] && [ ! -L "$entry" ]; then
            continue
        fi
        case "$entry" in
            "$runs_root"/run-*) ;;
            *)
                echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=path_boundary path=$entry"
                status=1
                continue
                ;;
        esac
        if [ -L "$entry" ]; then
            echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=run_symlink path=$entry"
            status=1
            continue
        fi
        if [ ! -d "$entry" ]; then
            echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=run_not_directory path=$entry"
            status=1
            continue
        fi
        count=$((count + 1))
        # shellcheck disable=SC2016
        size_kib=$(/musl/busybox du -sk "$entry" 2>/dev/null | /musl/busybox awk '{{print $1}}')
        case "$size_kib" in
            ''|*[!0-9]*) size_kib=unknown ;;
        esac
        echo "STARFIVE_SD_MAINTENANCE_ITEM action=$action path=$entry size_kib=$size_kib"
        if [ "$action" = delete ]; then
            /musl/busybox rm -rf "$entry"
            if [ -e "$entry" ] || [ -L "$entry" ]; then
                echo "STARFIVE_SD_MAINTENANCE_REFUSE reason=delete_failed path=$entry"
                status=1
            else
                echo "STARFIVE_SD_MAINTENANCE_DELETED path=$entry"
            fi
        fi
    done
fi

/musl/busybox sync
echo "STARFIVE_SD_MAINTENANCE_FINAL action=$action status=$status count=$count"
/musl/busybox reboot -f
exit "$status"
'''


def build_maintenance_fit(
    kernel: Path,
    output: Path,
    *,
    action: str,
    image_size: int = 64 * 1024 * 1024,
    runner_output: Path | None = None,
) -> Path:
    kernel = kernel.resolve()
    output = output.resolve()
    sidecar = output.with_suffix(output.suffix + ".json")
    if not kernel.is_file():
        raise FileNotFoundError(f"RISC-V kernel does not exist: {kernel}")
    if output.exists() or sidecar.exists():
        raise FileExistsError(f"refusing to replace maintenance output: {output}")
    if runner_output is not None:
        runner_output = runner_output.resolve()
        if runner_output.exists():
            raise FileExistsError(
                f"refusing to replace maintenance runner disk: {runner_output}"
            )
        if runner_output in {kernel, output, sidecar}:
            raise ValueError("maintenance runner output collides with another artifact")
    if image_size < 8 * 1024 * 1024:
        raise ValueError("maintenance ramdisk must be at least 8 MiB")
    for command in ("mkfs.ext4", "riscv64-linux-gnu-objcopy", "dtc", "fdtget"):
        if shutil.which(command) is None:
            raise RuntimeError(f"missing required offline command: {command}")

    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="whusp-starfive-maintenance-", dir="/tmp"
    ) as temp:
        temp_root = Path(temp)
        staging = temp_root / "staging"
        staging.mkdir()
        entry = staging / "entry.sh"
        entry.write_text(
            maintenance_entry_script(action), encoding="utf-8", newline="\n"
        )
        entry.chmod(0o755)
        runner_disk = temp_root / "maintenance.img"
        with runner_disk.open("wb") as image:
            image.truncate(image_size)
        subprocess.run(
            [
                "mkfs.ext4",
                "-q",
                "-F",
                "-N",
                "256",
                "-O",
                "^orphan_file,^metadata_csum_seed,^metadata_csum,^64bit,^has_journal",
                "-d",
                str(staging),
                str(runner_disk),
            ],
            check=True,
        )
        if runner_output is not None:
            runner_output.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(runner_disk, runner_output)
        environment = os.environ.copy()
        environment.update(
            {
                "STARFIVE_KERNEL_ELF": str(kernel),
                "STARFIVE_RUNNER_DISK": str(runner_disk),
                "STARFIVE_FIT_OUTPUT": str(output),
            }
        )
        subprocess.run(
            [str(REPO_ROOT / "scripts" / "build_starfive_fit.sh")],
            cwd=REPO_ROOT,
            env=environment,
            check=True,
        )

    metadata = {
        "schema": "whusp-starfive-sd-maintenance-v1",
        "created_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "action": action,
        "runs_root": "/work/.whusp-buildstorm-runs",
        "match": "run-*",
        "kernel": str(kernel),
        "kernel_sha256": sha256_file(kernel),
        "fit": str(output),
        "fit_sha256": sha256_file(output),
        "runner_disk": None if runner_output is None else str(runner_output),
        "runner_disk_sha256": (
            None if runner_output is None else sha256_file(runner_output)
        ),
    }
    sidecar.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"built StarFive SD maintenance FIT: {output}")
    print(f"action={action} sha256={metadata['fit_sha256']}")
    return output


def parse_size(value: str) -> int:
    suffixes = {"M": 1024**2, "G": 1024**3}
    suffix = value[-1:].upper()
    if suffix in suffixes:
        number = value[:-1]
        multiplier = suffixes[suffix]
    else:
        number = value
        multiplier = 1
    try:
        return int(number) * multiplier
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"invalid image size: {value}") from error


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="build a RAM-loaded FIT for safe BuildStorm run-directory maintenance"
    )
    parser.add_argument("--kernel", type=Path, default=REPO_ROOT / "kernel-rv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--action", choices=["list", "delete"], default="list")
    parser.add_argument("--image-size", type=parse_size, default=64 * 1024 * 1024)
    parser.add_argument(
        "--runner-output",
        type=Path,
        help="optionally keep the generated x1 disk for an offline QEMU boot",
    )
    parser.add_argument(
        "--confirm-delete",
        help=f"required for delete action; must equal {DELETE_CONFIRMATION}",
    )
    args = parser.parse_args(argv)
    if args.action == "delete" and args.confirm_delete != DELETE_CONFIRMATION:
        parser.error(f"delete action requires --confirm-delete {DELETE_CONFIRMATION}")
    if args.action == "list" and args.confirm_delete:
        parser.error("--confirm-delete is only valid with --action delete")
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    build_maintenance_fit(
        args.kernel,
        args.output,
        action=args.action,
        image_size=args.image_size,
        runner_output=args.runner_output,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
