#!/usr/bin/env python3
"""Export the final-round CAgent and BuildStorm guest runner."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import shutil
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = REPO_ROOT / "contest-case-commands"
MARKER_FILE = ".generated-by-export-contest-case-scripts"

RUN_CAGENT = True
RUN_BUILDSTORM = False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the script disk entry point for the 2026 final-round "
            "CAgent and BuildStorm tests."
        )
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help=f"output directory (default: {DEFAULT_OUT_DIR})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing directory created by this exporter",
    )
    return parser.parse_args()


def output_lock_path(path: Path) -> Path:
    digest = hashlib.sha256(str(path.resolve()).encode()).hexdigest()[:16]
    return Path("/tmp") / f"whusp-export-final-case-scripts-{digest}.lock"


@contextmanager
def output_lock(path: Path) -> Iterator[None]:
    with output_lock_path(path).open("w", encoding="utf-8") as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        yield


def prepare_out_dir(path: Path, force: bool) -> None:
    if path.exists():
        marker = path / MARKER_FILE
        if not force:
            raise FileExistsError(f"{path} already exists; pass --force to replace it")
        if not marker.exists():
            raise FileExistsError(
                f"{path} does not look generated; refusing to replace it"
            )
        shutil.rmtree(path)
    path.mkdir(parents=True)
    (path / MARKER_FILE).write_text(
        "Generated by scripts/export_contest_case_scripts.py for the final round.\n",
        encoding="utf-8",
    )


def enabled_default(enabled: bool) -> str:
    return "1" if enabled else "0"


def entry_script(run_cagent: bool, run_buildstorm: bool) -> str:
    return f"""#!/musl/busybox sh
# Generated final-round runner.

run_cagent="{enabled_default(run_cagent)}"
run_buildstorm="{enabled_default(run_buildstorm)}"

export PATH="/glibc:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TERM="vt220"

is_enabled() {{
    case "$1" in
        1|yes|true|on) return 0 ;;
        *) return 1 ;;
    esac
}}

run_case() {{
    case_name="$1"
    shift

    echo "FINAL: starting $case_name"
    (
        cd /glibc || exit 1
        "$@"
    )
    case_status=$?
    echo "FINAL: finished $case_name (status=$case_status)"
    return "$case_status"
}}

overall_status=0

if is_enabled "$run_cagent"; then
    if [ ! -f /glibc/cagent_testcode.sh ]; then
        echo "FINAL: cagent-glibc skipped: missing /glibc/cagent_testcode.sh"
        overall_status=1
    else
        run_case "cagent-glibc" /glibc/cagent_testcode.sh ||
            overall_status=1
    fi
else
    echo "FINAL: cagent-glibc disabled"
fi

if is_enabled "$run_buildstorm"; then
    if [ ! -f /glibc/buildstorm_testcode.sh ]; then
        echo "FINAL: buildstorm-glibc skipped: missing /glibc/buildstorm_testcode.sh"
        overall_status=1
    else
        run_case "buildstorm-glibc" /glibc/buildstorm_testcode.sh ||
            overall_status=1
    fi
else
    echo "FINAL: buildstorm-glibc disabled"
fi

echo "FINAL: all enabled tests finished (status=$overall_status)"

if /musl/busybox grep -q '^perf_counters_enabled 1$' /proc/oskernel/perf 2>/dev/null; then
    echo "#### KERNEL PERF START ####"
    /musl/busybox cat /proc/oskernel/perf
    echo "#### KERNEL PERF END ####"
fi

/musl/busybox sync
/musl/busybox reboot -f
exit "$overall_status"
"""


def readme(run_cagent: bool, run_buildstorm: bool) -> str:
    return f"""# Final Contest Case Commands

Generated by `scripts/export_contest_case_scripts.py`.

The entry script runs the final-round tests from the primary test disk:

- `/glibc/cagent_testcode.sh`
- `/glibc/buildstorm_testcode.sh`

Generated defaults:

- CAgent: {"enabled" if run_cagent else "disabled"}
- BuildStorm: {"enabled" if run_buildstorm else "disabled"}

Edit the switches near the top of the exporter:

```python
RUN_CAGENT = {run_cagent}
RUN_BUILDSTORM = {run_buildstorm}
```
"""


def write_outputs(
    out_dir: Path, force: bool, run_cagent: bool, run_buildstorm: bool
) -> None:
    with output_lock(out_dir):
        prepare_out_dir(out_dir, force)
        entry_path = out_dir / "entry.sh"
        entry_path.write_text(
            entry_script(run_cagent, run_buildstorm),
            encoding="utf-8",
            newline="\n",
        )
        entry_path.chmod(0o755)
        (out_dir / "README.md").write_text(
            readme(run_cagent, run_buildstorm),
            encoding="utf-8",
            newline="\n",
        )


def main() -> int:
    args = parse_args()
    write_outputs(
        args.out_dir.resolve(),
        args.force,
        RUN_CAGENT,
        RUN_BUILDSTORM,
    )
    print(
        f"wrote final-round runner to {args.out_dir} "
        f"(cagent={'on' if RUN_CAGENT else 'off'}, "
        f"buildstorm={'on' if RUN_BUILDSTORM else 'off'})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
